# https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-and-phpmyadmin-with-docker-compose-on-ubuntu-14-04
#
# run: docker-compose up -d
#
# => WP-sources under ./src
wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - "3000:80"
  volumes:
    - ./src:/var/www/html
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: changeme
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: changeme
    MYSQL_ROOT_PASSWORD: changeme